export const ADD_ARTISTS = 'ADD_ARTISTS';
export const ARTISTS_LOADING = 'ARTISTS_LOADING';
export const ARTISTS_FAILED = 'ARTISTS_FAILED';

export const ADD_GALLERIES = 'ADD_GALLERIES';
export const GALLERIES_LOADING = 'GALLERIES_LOADING';
export const GALLERIES_FAILED = 'GALLERIES_FAILED';

export const ADD_GALLERYIMAGES = 'ADD_GALLERYIMAGES';
export const GALLERYIMAGES_LOADING = 'GALLERYIMAGES_LOADING';
export const GALLERYIMAGES_FAILED = 'GALLERYIMAGES_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEW';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const ADD_BILLBOARDS = 'ADD_BILLBOARDS';
export const BILLBOARDS_LOADING = 'BILLBOARDS_LOADING';
export const BILLBOARDS_FAILED = 'BILLBOARDS_FAILED';

export const ADD_SHOPPING = 'ADD_SHOPPING';
export const SHOPPING_LOADING = 'SHOPPING_LOADING';
export const SHOPPING_FAILED = 'SHOPPING_FAILED';

export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_NEWS = 'ADD_NEWS';
export const NEWS_LOADING = 'NEWS_LOADING';
export const NEWS_FAILED = 'NEWS_FAILED';

export const ADD_MATCHES = 'ADD_MATCHES';
export const MATCHES_LOADING = 'MATCHES_LOADING';
export const MATCHES_FAILED = 'MATCHES_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';
